language: java

jdk:
  - oraclejdk8

sudo: required
dist: trusty

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

install: true

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./gradlew clean setupCIWorkspace assemble; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew clean setupCIWorkspace build; fi'