language: java

jdk:
  - oraclejdk8

sudo: required
dist: trusty

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
  - rm -f  $HOME/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/.gradle/minecraft/

before_install:
  - openssl aes-256-cbc -K $encrypted_9c31245b7f16_key -iv $encrypted_9c31245b7f16_iv -in keystore.jks.enc -out keystore.jks -d
  - chmod +x gradlew

install: true

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./gradlew clean setupCIWorkspace assemble; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew clean setupCIWorkspace build; fi'
